
            <div class="row">
                <div class="col-sm-4">
                    <h1></h1>
                    <?php if ($this->errMessage) : ?><p class="alert alert-danger"><?php echo $this->errMessage ?></p><?php endif; ?>
                    <?php echo $this->form ?>
                    <a href="/registration/forgotpass"><?php echo $this->translate('Forgot your password?') ?></a> | <a href="/registration"><?php echo $this->translate('Registration') ?></a>
                </div>
            </div>

