<div class="row">
    <div class="col-sm-4">
        <h2>Начисление процентов</h2>
        <div class="alert alert-warning">
            Начисление процентов может занять некоторое время.
        </div>
        <form role="form" method="post">
            <div class="input-group">
                <input type="text" class="form-control" name="percent" <?= $this->isDay !== false ? 'disabled' : ''?>>
                <span class="input-group-addon">%</span>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-danger" <?= $this->isDay !== false ? 'disabled' : ''?>>Начислить</button>
                </span>
            </div>
        </form>
    </div>
    <div class="col-sm-8">
        <div id="myfirstchart" style="height: 250px;"></div>
    </div>
</div>
<div class="row">
    <?= $this->daystable($this->days) ?>
</div>

<?php $this->headLink()->appendStylesheet('http://cdn.oesmith.co.uk/morris-0.4.3.min.css'); ?>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
<script>
    new Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'myfirstchart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: [
            <?php foreach($this->days as $day)
                echo '{ day: \'' . $day->date . '\', balance: ' . $day->balance . ' },';
            ?>
        ],
        // The name of the data record attribute that contains x-values.
        xkey: 'day',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['balance'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['Баланс']
    });
</script>
