
<div class="row">
    <div class="col-sm-8">
        <h3>Личный кабинет <small><?= $this->profile->name ?></small></h3>
        Ваш баланс: <strong><?= $this->number($this->profile->balance, '', '$') ?></strong>
        <span class="sm"><a href="#">пополнить</a> | <a href="/profile/moneyout">обналичить</a></span>
        <div id="balance" style="height: 150px;"></div>
        <hr/>
        <h3>Последние операции</h3>
        <?= $this->eventstable($this->events, 10) ?>
    </div>
    <div class="col-sm-4">
        <h3><span class="glyphicon glyphicon-align-justify"></span> Меню пользователя</h3>
        <nav>
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="/profile">Обзор</a></li>
                <li><a href="/profile/settings">Настройки</a></li>
                <li><a href="/profile/history">Операции</a></li>
                <li><a href="/profile/requests">Заявки</a></li>
                <li><a href="/profile/partner">Партнерская программа</a></li>
            </ul>
        </nav>
    </div>
</div>

<?php $this->headLink()->appendStylesheet('http://cdn.oesmith.co.uk/morris-0.4.3.min.css'); ?>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
<script>
    new Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'balance',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: [
            <?php foreach($this->days as $day)
                echo '{ day: \'' . $day->date . '\', balance: ' . $day->balance . ' },';
            ?>
        ],
        // The name of the data record attribute that contains x-values.
        xkey: 'day',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['balance'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['Баланс'],
        hideHover: 'auto',
        pointSize: 2,
        postUnits: ' $'
    });
</script>