<div class="row">
    <div class="col-sm-4">
        <h3>Настройки аккаунта</h3>
        <?= $this->form ?>
    </div>
    <div class="col-sm-4">
        <h3>Изменить пароль</h3>
        <?= $this->form_password ?>
    </div>
    <div class="col-sm-4">
        <h3><span class="glyphicon glyphicon-align-justify"></span> Меню пользователя</h3>
        <nav>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="/profile">Обзор</a></li>
                <li class="active"><a href="/profile/settings">Настройки</a></li>
                <li><a href="/profile/history">Операции</a></li>
                <li><a href="/profile/requests">Заявки</a></li>
                <li><a href="/profile/partner">Партнерская программа</a></li>
            </ul>
        </nav>
    </div>
</div>